name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@a5dd21fa281a9804e7c1f1cf3e522bc05d982e8a
      with:
        action_config_path: '.github/config/rubocop_linter_config.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
